### ISSUE TITLE
CRI-O updates / run-through

### ISSUE THREAD

**Issue by dougbtv** [redhat-nfvpe/kube-ansible#114]
CRI-O and Buildah seem to be broken as of the #113 PR, I believe that likely there are upstream changes to CRI-O and Buildah that may have impacted the functionality of these roles, and not due to the change in method for installing golang. 

That being said, it needs to have a run-through to make sure it's functional.

**Comment by s1061123** [comment]
#276 fixes the issue, I hope. Hence closed.
