### ISSUE TITLE
Some galaxy role variables are undefined

### ISSUE THREAD

**Issue by dougbtv** [redhat-nfvpe/kube-ansible#134]
Specifically I ran into `perform_hardware_checks` from the [auto-kube-dev](https://github.com/redhat-nfvpe/auto-kube-dev) role was missing, it's in `group_vars/all*` but isn't picked up.

To replicate, give yourself a new clone, install the requirements.yml, specify you want a builder VM, run virthost-setup, then run the builder playbook.

**Comment by leifmadsen** [comment]
@dougbtv do you have an output you could paste here? I think I know at least 2 things that are missing that would be easy to fix, I just want to see where it initially fails.

The first one I can think of, is that the `builder` VM I don't think is built initially. There is no `builder` VM in the `virtual_machines` list, so at the very least, you need to add `builder` to the `virtual_machines` list.

**Comment by dougbtv** [comment]
Turns out, I can no longer replicate this, so it must've shaken out in other fixes, thanks for double checking!
