### ISSUE TITLE
auto-kube-dev assertions only need to be done on initial deploy

### ISSUE THREAD

**Issue by leifmadsen** [redhat-nfvpe/kube-ansible#136]
When using auto-kube-dev with kube-centos-ansible, the assertions on disk size checks don't take into account that you might actually use the builder VM, and run subsequent runs. After a first successful build, if you run the `builder.yml` again, then you'll fail the disk space assertions (since you've used the disk space up with the kubernetes repo clone, and build artifacts).

We should clean this up so that the assertions only care on initial run. We could either add a `.assertions_ok` dotfile, or change the `size_available` to only check for the size of the disk itself (i.e. assume things are fine if the disk is sized correctly, and not worry about actual free space).

The current work around is to pass `-e "perform_hardware_checks=false` to the `ansible-playbook` run on subsequent runs.

**Comment by dougbtv** [comment]
Moved to https://github.com/redhat-nfvpe/auto-kube-dev/issues/16
