### ISSUE TITLE
[network] Support kokonet

### ISSUE THREAD

**Issue by s1061123** [redhat-nfvpe/kube-ansible#157]
May need some features as following (to be added when I found...

- [x] Add node_type for non k8s node (to install vpp for switch)
- [x] Support multiple network in virthost

**Comment by s1061123** [comment]
https://github.com/redhat-nfvpe/ansible-role-vm-spinup/pull/4 adds multiple network support in virthost.

**Comment by leifmadsen** [comment]
@s1061123 what is the status on this? Did you complete this? :)
