### ISSUE TITLE
[network] kokonet's kube-dns goes fail without "apiserver-advertise-address"

### ISSUE THREAD

**Issue by s1061123** [redhat-nfvpe/kube-ansible#170]

**Comment by leifmadsen** [comment]
Curious if we're closer to solving this after some recent changes?

**Comment by s1061123** [comment]
well, without kube-ansible, sometimes failed so i suppose there might be non kube-ansible related.
anyway, i'll try again with latest one in my spare time...

**Comment by s1061123** [comment]
#202 removes 'apiserver-advertise-address' in playbook because I verified that it works.
