### ISSUE TITLE
[network] kube-dns failing with Multus with CRD enabled

### ISSUE THREAD

**Issue by dougbtv** [redhat-nfvpe/kube-ansible#172]
Apparently the kube-dns pod is complaining that it couldn't get a sandbox created. Sounds a lot like something wrong with CNI, as that looks rather familiar from seeing a CNI plugin not properly return.

Likely the kube-dns pod is going to run on the master (or that'd be my guess) wonder if there's some missing CNI setup there. 

As reported by @fepan

**Comment by leifmadsen** [comment]
Test comment.

**Comment by dougbtv** [comment]
Per fepan:

> oh by the way, you know the dns problem i was telling you about with multus, it turns out the reason is that you need to configure the default network for multus, the error i saw was that multus complained it couldn't figure out the network for dns pod

Feng added this to the cni config:

```
"delegates": [{"type": "flannel", "isDefaultGateway": true, "masterplugin": true}]
```

**Comment by Elegant996** [comment]
Not quite! That should not work as you are still missing a delegate within delegates. I believe the solution you are seek is: 

```
  "delegates": [
	{
	  "type": "flannel",
	  "masterplugin": true,
	  "delegate": {
		"isDefaultGateway": true
	  }
	}
  ],`
```

Once I used that, my DNS pod spun up with ease. Thanks!

**Comment by Elegant996** [comment]
The correct code block should be:
```
    "delegates": [
	  {
        "type": "flannel",
        "masterplugin": true,
        "delegate": {
          isDefaultGateway": true
        }
      }
    ],
```
There may still be an issue regarding permissions. I realize that ClusterRoleBinding is created for the master and each node but that seems to have little effect and Flannel is being defaulted. Perhaps someone else can confirm as this expands upon the same issue. Thanks!

**Comment by dougbtv** [comment]
@Elegant996 -- thank you a bunch for the input! Thanks for looking into it, and giving some feedback. Really happy to have any further input on my findings here.

Regarding permissions, there should be a service account created for flannel in the [multus-crd.yaml.j2](https://github.com/redhat-nfvpe/kube-ansible/blob/master/roles/kube-template-cni/templates/multus-crd.yaml.j2). As you've seen there are rather liberal clusterroles/clusterrolebindings created, [in this task](https://github.com/redhat-nfvpe/kube-ansible/blob/master/roles/multus-crd/tasks/main.yml#L76), to allow Multus to pull the CRDs.

Unfortunately, I didn't have luck with your suggested code block, which wound up looking like this in my template:

```
  cni-conf.json: |
    {
      "name": "multus-cni-network",
      "type": "multus",
      "delegates": [
        {
          "type": "flannel",
          "masterplugin": true,
          "delegate": {
            isDefaultGateway": true
          }
        }
      ],
      "kubeconfig": "/etc/kubernetes/kubelet.conf"
    }
```

Is it possible that I missed out on something here? I might've overlooked something, for sure.

I did have success with this block:

```
  cni-conf.json: |
    {
      "name": "multus-cni-network",
      "type": "multus",
      "delegates": [{"type": "flannel", "isDefaultGateway": true, "masterplugin": true}],
      "kubeconfig": "/etc/kubernetes/kubelet.conf"
    }
```
Which allowed for kube-dns pods to come up.

**Comment by snowmansora** [comment]
@dougbtv kube-dns fails when I used your block:
```
cni-conf.json: |
    {
      "name": "multus-cni-network",
      "type": "multus",
      "delegates": [{"type": "flannel", "isDefaultGateway": true, "masterplugin": true}],
      "kubeconfig": "/etc/kubernetes/kubelet.conf"
    }
````
However, kube-dns works when I used @Elegant996 block after adding a **missing double quote** before isDefaultGateway:
```
  cni-conf.json: |
    {
      "name": "multus-cni-network",
      "type": "multus",
      "delegates": [
        {
          "type": "flannel",
          "masterplugin": true,
          "delegate": {
            "isDefaultGateway": true
          }
        }
      ],
      "kubeconfig": "/etc/kubernetes/kubelet.conf"
    }
```

However, I am not able to get pod running with both flannel and macvlan network like _both.pod.yaml_ in your blog (http://dougbtv.com/nfvpe/2017/12/19/multus-crd/). The pod only has the flannel network. Not sure what is wrong at the moment.
**Update (1)**: A permission problem, see https://github.com/Intel-Corp/multus-cni/issues/42

Also, I have added the followings to roles/kube-template-cni/templates/flannel-rbac.yaml.j2:
```
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
```
Because the log complains about permission, though I am not sure whether it is related to kube-dns issue.
**Update (1)**: Above permission also exists in https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

p.s. I am using latest code on master branch, testing it on CentOS 7.4.

**Comment by dougbtv** [comment]
@snowmansora -- thank you a bunch for both giving it a go, and especially for the particularly detailed comment, and finding that missing double quote!

I've got a pull request opened #173 which includes the fixed up block with missing quote -- if you could give it a look and see if you have any better luck, I'd love any input there.

Thanks for the pointer to the updated Flannel RBAC -- I went ahead and included that in the file as you've suggested. You'll see the diff in #173 as well.

Regarding the Multus permissions, I went ahead and also commented on the linked issue in the Multus repo.

Regarding not being able to use macvlan -- there's a possibility that it's having some trouble using network settings that are not usable on your network? I'm unsure.

At any rate -- if you could send me the output of the generated `macvlan.yml` file on your master node, such as...

```
[centos@origkube-master ~]$ cat ~/multus-resources/macvlan.yml 
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: macvlan-conf
plugin: macvlan
args: '[
        {
            "master": "eth0",
            "mode": "bridge",
            "ipam": {
                "type": "host-local",
                "subnet": "192.168.1.0/24",
                "rangeStart": "192.168.1.200",
                "rangeEnd": "192.168.1.216",
                "routes": [
                    { "dst": "0.0.0.0/0" }
                ],
                "gateway": "192.168.1.1"
            }
        }
]'
```

I do think there's a number of issues here, and if you care to open issues for each of the portions, I'd be happy to tackle them individually, too.

Thanks again for the input and giving it a try!!

edit: p.s. welcome to github!

**Comment by Elegant996** [comment]
Thanks for spotting the double quote, I forgot it when I was writing it out again.

**Comment by snowmansora** [comment]
@dougbtv 
I am able to setup a K8s Multus environment with your change in #173 pull request AND 2 additional changes before running Ansible playbook "kube-install.yml":

1. Update flannel image from 0.7.0 to 0.7.1 in "roles/kube-template-cni/templates/multus-crd.yaml.j2" as suggested by https://github.com/coreos/flannel/issues/688. Note that I am NOT 100% sure whether this is required or not as I encountered the problem previously on some old setup, and have used 0.7.1 since then.
2. Update "inventory_hostname" to "ansible_nodename" in "roles/multus-crd/tasks/main.yml" for case where IP is used in Ansible inventory (see https://github.com/Intel-Corp/multus-cni/issues/42#issuecomment-366881311 for details).

The macvlan is okay after I applied point 2 above.

Thank you very much for all your works on kube-ansible!

**Comment by dougbtv** [comment]
@snowmansora -- most excellent -- thanks for testing those out and giving some feedback. 

I'm happy to integrate those changes, I went ahead and made those changes and tested them out in my own environment, and they worked just fine. I've gone ahead and amended my commit on PR #173 -- it both upgrades to flannel 0.7.1 image tag, and then uses ansible_nodename. 

I can't say for sure either what impact 0.7.0 vs 0.7.1 has, however, it's now making me wonder if we need to update flannel to an even newer version, as this version has been sitting in here for quite some time. I'll open another issue.

Regarding 2. above, yep, seems perfect if you've got the IP in the inventory. Good eye.

If there's any chance you can try again with the same PR, I'd appreciate it a ton. Again, thanks for your input, and giving it some exercise!

**Comment by verizonold** [comment]
@dougbtv  I am running into problems with DNS starting up:
pr 07 02:03:42 kubecrd-minion1 kubelet[2301]: E0407 02:03:42.155987    2301 pod_workers.go:186] Error syncing pod 5f9bbd7e-39fe-11e8-8556-525400daa710 ("kube-dns-86f4d74b45-mbdd8_kube-system(5f9bbd7e-39fe-11e8-8556-525400daa710)"), skipping: failed to "CreatePodSandbox" for "kube-dns-86f4d74b45-mbdd8_kube-system(5f9bbd7e-39fe-11e8-8556-525400daa710)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-dns-86f4d74b45-mbdd8_kube-system(5f9bbd7e-39fe-11e8-8556-525400daa710)\" failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod \"kube-dns-86f4d74b45-mbdd8_kube-system\" network: Multus: Err in getting k8s network from pod: no kubernetes network found"

Any pointers?
