### ISSUE TITLE
[network] bridge.yaml DHCP issues

### ISSUE THREAD

**Issue by Elegant996** [redhat-nfvpe/kube-ansible#174]
Hello,
I recently tried deploying [bridge.yaml](https://github.com/redhat-nfvpe/kube-ansible/blob/master/roles/kube-template-cni/templates/bridge.yaml.j2) but am always met with the following:

```
pod_container_deletor.go:77] Container "e863e5d86b09d0577ffad341f7e4af3bfbbb61029c36c344be3950d690f76867" not found in pod's containers
cni.go:259] Error adding network: error calling DHCP.Allocate: no more tries
cni.go:227] Error while adding to cni network: error calling DHCP.Allocate: no more tries
remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = NetworkPluggin cni failed to set up pod "testpod__default" network: error calling DHCP.Allocate: no more tries
```

Not sure if I'm missing anything; my DHCP server is running just fine on my gateway. Thanks!

**Comment by s1061123** [comment]
Well, this message indicates that CNI dhcp plugin just timeouted with retry (3 times).
This yaml file is based on libvirt environment (including dhcp, dnsmasq, as default config), so please change bridge.yaml if you change dhcp server configuration.

In addition, this yaml file requires 'bridge-setup' role and others (e.g. create bridge 'cni0').
If you just did 'kubectl apply bridge.yaml' before, could you try ansible-playbook with 'network_type: bridge' in virthost yaml file from scratch?

**Comment by Elegant996** [comment]
Not entirely sure what I might need to change for my environment, I have a DHCP server on a separate VM providing leases (ISC). I ended up redoing my entire setup as I'm looking to expand on a few things (VLANs, etc.). That being said, I have the following working:

ifcfg-br0
```
DEVICE=br0
TYPE=Bridge
BOOTPROTO=dhcp
NAME=br0
UUID=73ab24fd-a663-4383-b260-8bad8d9d0579
ONBOOT=yes
PEERDNS="yes"
IPV6INIT="no"
PERSISTENT_DHCLIENT="1"
DELAY=0
```
and

ifcfg-bridge-slave-ens160.30
```
VLAN=yes
TYPE=Vlan
DEVICE=ens160.30
PHYSDEV=ens160
VLAN_ID=30
REORDER_HDR=yes
GVRP=no
MVRP=no
NAME=bridge-slave-ens160.30
UUID=2fb7e201-f06c-4bcc-a426-ef8c5d922c95
ONBOOT=yes
BRIDGE=br0
```

Which both workout as seen below:
```
# ip a s br0
5: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:0c:29:61:6b:ad brd ff:ff:ff:ff:ff:ff
    inet 10.0.30.178/24 brd 10.0.30.255 scope global dynamic br0
       valid_lft 6810sec preferred_lft 6810sec
    inet6 fe80::20c:29ff:fe61:6bad/64 scope link
       valid_lft forever preferred_lft forever
```

I then updated bridge.yaml to use `br0` instead of `cni0` as that should be the only change required but the same issue persists. I'm not sure what else I'm missing or if it's still related to bridge.yaml but any help would be appreciated. Thanks!

**Comment by s1061123** [comment]
Did you add `--extra-vars "pod_network_type=bridge"` in ansible-playbook kube-install.yml?

```
# ansible-playbook -i ./inventory/vms.local.generated --extra-vars "pod_network_type=bridge" kube-install.yml
```

This changes master/minion's interface as following:
- create bridge cni0 instead of br0, and
- attach eth0 into cni0

```
[centos@kube-master ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master cni0 state UP qlen 1000
    link/ether 52:54:00:c1:1f:f3 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::5054:ff:fec1:1ff3/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN
    link/ether 02:42:76:c6:1c:e7 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
4: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether 52:54:00:c1:1f:f3 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.174/24 brd 192.168.122.255 scope global dynamic cni0
       valid_lft 3358sec preferred_lft 3358sec
    inet6 fe80::5054:ff:fec1:1ff3/64 scope link
       valid_lft forever preferred_lft forever
```

In addition, you may need to change ```"nameservers:"``` in [bridge.yaml](https://github.com/redhat-nfvpe/kube-ansible/blob/master/roles/kube-template-cni/templates/bridge.yaml.j2) to adjust your config.
Hope you will be succeed to config with above info...

**Comment by Elegant996** [comment]
Yep, no luck. I've tried to do a lot more digging and it seems that my DHCP server does not even see the requests coming in.

It's very reminiscent of some of the issues found on the cni repo. Very odd...

**Comment by Elegant996** [comment]
I was successful in getting macvlan working instead so this isn't really an issue worth pursuing now. I have seem similar reports though (macvlan working; bridge not). Closing this for now. Thanks!

**Comment by s1061123** [comment]
Found some configuration issue for bridge-network. #202 fixes the issues.

Just FYI.
