### ISSUE TITLE
[system] Docker 1.13 causes issues with Flannel networking

### ISSUE THREAD

**Issue by leifmadsen** [redhat-nfvpe/kube-ansible#200]
When using Docker 1.13 (which is the new latest version on CentOS 7.4), issues are had around the flannel networking. Pods are no longer able to communicate with the outside world. Flannel spins up no problem, and you can ping the gateway interface (10.244.1.1) but pods can't ping to 4.2.2.2 for example, and you can't communicate with the services over the flannel network (like `curl http://10.244.3.3:8080/hello`).

Related to #199

**Comment by dougbtv** [comment]
Root cause is Flannel 0.7.x not behaving nicely with Docker 1.13. However, Flannel 0.10.x behaves nicely with both Docker 1.13 & 1.12.
