### ISSUE TITLE
Problem with using Kubernetes Dashboard

### ISSUE THREAD

**Issue by verizonold** [redhat-nfvpe/kube-ansible#223]
Hi @dougbtv  @leifmadsen ,
I had a pretty successful deployment of multus+CRD and am able to see multiple network interfaces in the POD's.
However, when I deploy the Kubernetes dashboard using the directons at: https://github.com/kubernetes/dashboard, I get the following error:
Error: 'dial tcp 10.244.1.3:8443: getsockopt: connection timed out'
Trying to reach: 'https://10.244.1.3:8443/'

and 10.244.1.3 is the IP of my dashboard.

I am running kubectl proxy and using the following URL as prescribed:
http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

I have also applied the dashboard-admin.yaml as per the directions here:
https://github.com/kubernetes/dashboard/wiki/Access-control

Any help is much appreciated.

**Comment by dougbtv** [comment]
@verizonold -- any input on the resolution? Was it just an issue routing traffic to the machine? It kind of sounded like that originally. Thanks!

**Comment by verizonold** [comment]
@dougbtv yes, it is still a routing traffic issue which I am not sure how to resolve. I thought all pods were reachable from master as per CNI spec and flannel/multus implementation. Basically, the dashboard pod deployed on a minion is not accessible from master. For now, I forced the deployment on master which has resolved my issue for now. Any input on how to resolve the reach ability issue is much appreciated.
