### ISSUE TITLE
DNS Container remains in ContainerCreating status

### ISSUE THREAD

**Issue by verizonold** [redhat-nfvpe/kube-ansible#228]
@dougbtv 
I see the following error and kube-dns containers remain in ContainerCreating. I do see /run/flannel/subnet.env file on master, so not sure why it complains.

Events:
  Type     Reason                  Age                From                 Message
  ----     ------                  ----               ----                 -------
  Warning  FailedScheduling        6m (x3 over 6m)    default-scheduler    0/1 nodes are available: 1 node(s) were not r
eady.
  Warning  FailedScheduling        6m (x3 over 6m)    default-scheduler    0/2 nodes are available: 2 node(s) were not r
eady.
  Warning  FailedScheduling        6m (x2 over 6m)    default-scheduler    0/3 nodes are available: 3 node(s) were not r
eady.
  Normal   Scheduled               6m                 default-scheduler    Successfully assigned kube-dns-86f4d74b45-b6f
wp to kubemaster
  Normal   SuccessfulMountVolume   6m                 kubelet, kubemaster  MountVolume.SetUp succeeded for volume "kube-
dns-config"
  Normal   SuccessfulMountVolume   6m                 kubelet, kubemaster  MountVolume.SetUp succeeded for volume "kube-
dns-token-76fvt"
  Warning  FailedCreatePodSandBox  5m (x12 over 6m)   kubelet, kubemaster  Failed create pod sandbox: rpc error: code =
Unknown desc = NetworkPlugin cni failed to set up pod "kube-dns-86f4d74b45-b6fwp_kube-system" network: Multus: error in
invoke Delegate add - "flannel": open /run/flannel/subnet.env: no such file or directory
  Normal   SandboxChanged          1m (x286 over 6m)  kubelet, kubemaster  Pod sandbox changed, it will be killed and re
-created.

**Comment by verizonold** [comment]
I ran it again and now I see this error message:
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age               From                 Message
  ----     ------                  ----              ----                 -------
  Warning  FailedScheduling        3m (x6 over 3m)   default-scheduler    0/1 nodes are available: 1 node(s) were not ready.
  Normal   Scheduled               3m                default-scheduler    Successfully assigned kube-dns-86f4d74b45-hljvn to kubemaster
  Normal   SuccessfulMountVolume   3m                kubelet, kubemaster  MountVolume.SetUp succeeded for volume "kube-dns-config"
  Normal   SuccessfulMountVolume   3m                kubelet, kubemaster  MountVolume.SetUp succeeded for volume "kube-dns-token-zhr8v"
  Warning  FailedCreatePodSandBox  2m (x12 over 3m)  kubelet, kubemaster  Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "kube-dns-86f4d74b45-hljvn_kube-system" network: unexpected end of JSON input
  Normal   SandboxChanged          2m (x11 over 3m)  kubelet, kubemaster  Pod sandbox changed, it will be killed and re-created.

**Comment by verizonold** [comment]
@dougbtv The problem seems to be in /roles/kube-template-cni/templates/multus-crd.yaml.j2.
It has delegates as following:
"delegates": [
        {
          "type": "flannel",
          "name": "flannel.1",
          "subnetFile": "/run/flannel/subnet.env",
          "dataDir": "/var/lib/cni/flannel",
          "delegate": {
            "bridge": "kbr0",
            "isDefaultGateway": true
          }
        }

**Comment by verizonold** [comment]
@dougbtv This works:
"delegates": [
        {
          "type": "flannel",
          "masterplugin": true,
          "delegate": {
            "isDefaultGateway": true
          }
        }

**Comment by dougbtv** [comment]
Hey @verizonold  could you check and see if this is resolved / do you have any notes to add to resolve it? Thanks!

**Comment by verizonold** [comment]
@dougbtv yes sir...I do not see  this problem anymore.
