### ISSUE TITLE
Gluster ansible

### ISSUE THREAD

**Issue by verizonold** [redhat-nfvpe/kube-ansible#230]
Hi,
I have a kube ansible+multus setup and would like to add the gluster support. I attached /dev/sdb with vagrant and am running the following to get the gluster+heketi installation:
ansible-playbook -i ./inventory/comp.inventory ./playbooks/ka-gluster-install/gluster-in
stall.yml

However, I get the following error on kubemaster:

```
fatal: [kubemaster]: FAILED! => {"changed": true, "cmd": "./gk-deploy -n gluster -w 900 -g -y", "delta": "0:17:35.138915
", "end": "2018-06-04 19:04:42.523840", "msg": "non-zero return code", "rc": 1, "start": "2018-06-04 18:47:07.384925", "
stderr": "", "stderr_lines": [], "stdout": "Using Kubernetes CLI.\nNAME      STATUS    AGE\ngluster   Active    39s\nUsi
ng namespace \"gluster\".\nChecking that heketi pod is not running ... OK\nserviceaccount \"heketi-service-account\" cre
ated\nclusterrolebinding.rbac.authorization.k8s.io \"heketi-sa-view\" created\nnode \"kubeminion1\" labeled\nnode \"kube
minion2\" labeled\ndaemonset.extensions \"glusterfs\" created\nWaiting for GlusterFS pods to start ... pods not found.\n
Error from server (NotFound): services \"heketi\" not found\nserviceaccount \"heketi-service-account\" deleted\nNo resou
rces found\nError from server (NotFound): services \"heketi-storage-endpoints\" not found\nclusterrolebinding.rbac.autho
rization.k8s.io \"heketi-sa-view\" deleted\nError from server (NotFound): deployments.extensions \"heketi\" not found\nn
ode \"kubeminion1\" labeled\nnode \"kubeminion2\" labeled\ndaemonset.extensions \"glusterfs\" deleted", "stdout_lines":
["Using Kubernetes CLI.", "NAME      STATUS    AGE", "gluster   Active    39s", "Using namespace \"gluster\".", "Checkin
g that heketi pod is not running ... OK", "serviceaccount \"heketi-service-account\" created", "clusterrolebinding.rbac.
authorization.k8s.io \"heketi-sa-view\" created", "node \"kubeminion1\" labeled", "node \"kubeminion2\" labeled", "daemo
nset.extensions \"glusterfs\" created", "Waiting for GlusterFS pods to start ... pods not found.", "Error from server (N
otFound): services \"heketi\" not found", "serviceaccount \"heketi-service-account\" deleted", "No resources found", "Er
ror from server (NotFound): services \"heketi-storage-endpoints\" not found", "clusterrolebinding.rbac.authorization.k8s
.io \"heketi-sa-view\" deleted", "Error from server (NotFound): deployments.extensions \"heketi\" not found", "node \"ku
beminion1\" labeled", "node \"kubeminion2\" labeled", "daemonset.extensions \"glusterfs\" deleted"]}
```

**Comment by leifmadsen** [comment]
You'll need to look at the logs of the heketi installation. For some reason it's failing. Unfortunately heketi is a bit difficult to debug because the default is not to log very much.

**Comment by verizonold** [comment]
@leifmadsen @dougbtv What is the procedure to restart kube-ansible/gluster if the node IP changes?

**Comment by leifmadsen** [comment]
@verizonold I'd setup static IPs so that doesn't happen, and if it does, tear down the environment and redeploy. (Sorry, this isn't intended to be used for production.)

**Comment by verizonold** [comment]
@leifmadsen so what is the procedure to remove gluster from my kube-ansible deployment?
Is glusterfs-endpoints the only place where IP's are referenced?

**Comment by leifmadsen** [comment]
@verizonold I'm not sure what you mean by "remove gluster from your ansible deployment"?

**Comment by verizonold** [comment]
so I use kube-ansible to deploy kubernetes+multus+flannel....and then do a gluster deployment on top of this deployment. However, I just want to reinstall the gluster components since its now all messed up because of the change in IP of one of my VM's...

**Comment by leifmadsen** [comment]
@verizonold use `playbooks/ka-gluster-install`

**Comment by verizonold** [comment]
I have been using: ansible-playbook -i inventory/vms.inventory gluster-install.yml

How is this different from ka-gluster-install?

**Comment by leifmadsen** [comment]
Closing out an old issue
