### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by verizonold** [redhat-nfvpe/kube-ansible#236]
Hi @dougbtv  @leifmadsen @s1061123 ,
I now get the following error on a build.  Any help to fix it appreciated.
Thanks,
patram
[Document2.docx](https://github.com/redhat-nfvpe/kube-ansible/files/2150042/Document2.docx)

**Comment by dougbtv** [comment]
Any chance you can post a paste bin or something instead of the word doc? Thanks!

**Comment by verizonold** [comment]
@dougbtv 
http://pasteall.org/1008776

**Comment by verizonold** [comment]
@dougbtv  closing this since i do not have this issue as of now after doing a fresh build.
