### ISSUE TITLE
Install jq error

### ISSUE THREAD

**Issue by verizonold** [redhat-nfvpe/kube-ansible#256]
TASK [kubectl-proxy-systemd : Install jq binary] *******************************

Hi,
I get the following error with kube-ansible. Can you please shed some light on it?

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SSLError: ('The read operation timed out',)
fatal: [kubemaster]: FAILED! => {"changed": false, "msg": "failed to create temporary content file: ('The read operation timed out',)"}

PLAY RECAP *********************************************************************
kubemaster                 : ok=49   changed=28   unreachable=0    failed=1
kubeminion1                : ok=33   changed=17   unreachable=0    failed=0
kubeminion2                : ok=33   changed=17   unreachable=0    failed=0

**Comment by s1061123** [comment]
Sorry for late reply. It seems to failed to get jq binary due to timeout. Re-run may resolve issue.
Or you need to check download following URL "https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64" because some URL firewall/proxy may reject your request.
