### ISSUE TITLE
Need to migrate kubeadm.cfg.j2 to new API version

### ISSUE THREAD

**Issue by s1061123** [redhat-nfvpe/kube-ansible#261]
"apiVersion: kubeadm.k8s.io/v1alpha2" will be deprecated soon so we need to upgrade to "apiVersion: kubeadm.k8s.io/v1alpha3"

**Comment by dougbtv** [comment]
Good catch, I ran into this one too and have a fix in the ONS branch, maybe
we should decide if we want to merge that in -- I think overall it's a
benefit to merge it. But if you fix it up beforehand, that's ok, I can fix
the conflict

**Comment by s1061123** [comment]
Yeah, looking your ONS branch, you update to v1alpha2 and that could be enough for now.
But the latest is v1alpha3 and v1alpha3 changes a bit more so we merge your ONS branch first and let's update it to v1alpha3.

**Comment by s1061123** [comment]
fixed at #271
