### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by meragodbole** [redhat-nfvpe/kube-ansible#284]
Hi,
I get the followiong error when I run:
ansible-playbook -i inventory/comp.inventory playbooks/kube-install.yml

----------------------Cloning into 'kube-ansible'...
- extracting install-go to /home/vagrant/kube-ansible/roles/install-go
- install-go (master) was installed successfully
- extracting install-docker to /home/vagrant/kube-ansible/roles/install-docker
- install-docker (master) was installed successfully
- extracting auto-kube-dev to /home/vagrant/kube-ansible/roles/auto-kube-dev
- auto-kube-dev (master) was installed successfully
- extracting redhat-nfvpe.vm-spinup to /home/vagrant/kube-ansible/roles/redhat-nfvpe.vm-spinup
- redhat-nfvpe.vm-spinup (master) was installed successfully
- downloading role 'vm-infra', owned by oVirt
- downloading role from https://github.com/oVirt/ovirt-ansible-vm-infra/archive/1.1.11.tar.gz
- extracting oVirt.vm-infra to /home/vagrant/kube-ansible/roles/oVirt.vm-infra
- oVirt.vm-infra (1.1.11) was installed successfully
- extracting redhat-nfvpe.prometheus-operator to /home/vagrant/kube-ansible/roles/redhat-nfvpe.prometheus-operator
- redhat-nfvpe.prometheus-operator (master) was installed successfully
cp: cannot create regular file ‘./roles/multus-crd/tasks/main.yml’: No such file or directory
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/vagrant/kube-ansible/roles/kube-install/tasks/system_setup.yml': line 6, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: "reboot machine"
  ^ here

The error appears to have been in '/home/vagrant/kube-ansible/roles/kube-install/tasks/system_setup.yml': line 6, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: "reboot machine"
  ^ here

exception type: <class 'ansible.errors.AnsibleParserError'>
exception: no action detected in task. This often indicates a misspelled module name, or incorrect module path.

**Comment by meragodbole** [comment]
@leifmadsen - any input?

**Comment by meragodbole** [comment]
@dougbtv

**Comment by leifmadsen** [comment]
@meragodbole I suspect too old a version of Ansible and that you're missing the `reboot` module. Make sure you're using Ansible 2.7.1 or later.

**Comment by meragodbole** [comment]
@leifmadsen yessir, that worked. Closing
