### ISSUE TITLE
Template error while templating string: no filter named 'version_compare'.

### ISSUE THREAD

**Issue by jijianwen** [redhat-nfvpe/kube-ansible#304]
Got the following error when doing 'ansible-playbook -i ./inventory/vms.local.generated playbooks/kube-install.yml '. It seems version_compare has been removed.
My ansible version: 2.9.2

`
fatal: [kube-master]: FAILED! => {"msg": "The conditional check '(installed_docker_version.stdout | version_compare('1.13', '<')) and docker_repo_type == 'os'\n' failed. The error was: template error while templating string: no filter named 'version_compare'. String: {% if (installed_docker_version.stdout | version_compare('1.13', '<')) and docker_repo_type == 'os'\n %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/jijianwen/wks/repos/kube-ansible/roles/install-docker/tasks/docker_centos.yml': line 35, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# Ref: https://github.com/projectatomic/docker/issues/285\n- name: Update Docker systemd unit file\n  ^ here\n"}
`

**Comment by s1061123** [comment]
Hi, thank you for reporting issue!
I'm fixing it and put PR for that. Once fixed, please update playbook with `ansible-galaxy install -f -r requirements.yml`

**Comment by s1061123** [comment]
This is fixed in https://github.com/redhat-nfvpe/ansible-role-install-docker/pull/25, so closed the issue.

**Comment by jijianwen** [comment]
> This is fixed in [redhat-nfvpe/ansible-role-install-docker#25](https://github.com/redhat-nfvpe/ansible-role-install-docker/pull/25), so closed the issue.

It works for me.
