### ISSUE TITLE
Got 404 Not Found when accessing https://git.io/weave-kube

### ISSUE THREAD

**Issue by jijianwen** [redhat-nfvpe/kube-ansible#306]
After changing pod_network_type to 'weave', got error as below:
`
TASK [kube-cni : Apply the weave podnetwork] *****************************************************************************************************
fatal: [kube-master]: FAILED! => {"changed": true, "cmd": "kubectl apply -f https://git.io/weave-kube > /tmp/podnetwork-apply.log\n", "delta": "0:00:02.412719", "end": "2020-01-14 06:28:05.748333", "msg": "non-zero return code", "rc": 1, "start": "2020-01-14 06:28:03.335614", "stderr": "error: unable to read URL \"https://git.io/weave-kube\", server reported 404 Not Found, status code=404", "stderr_lines": ["error: unable to read URL \"https://git.io/weave-kube\", server reported 404 Not Found, status code=404"], "stdout": "", "stdout_lines": []}
`

**Comment by s1061123** [comment]
Without kube-ansible and kubernetes, https://git.io/weave-kube just returns 404 error. 

This means 'https://git.io/weave-kube' is no longer used. Could you ask weave community to get the latest (and valid) URL?

This issue is closed because it is not a kube-ansible issue.

**Comment by s1061123** [comment]
We're thinking to remove CNI configuration from kube-ansible playbook because nowadays all CNI plugin community provides 'kubectl create -f http://....' style installation method.

I'm working on #307 to remove it. Just FYI.
