### ISSUE TITLE
Deploying with pod_network_type = "multus" results in the master in "NotReady" state

### ISSUE THREAD

**Issue by vinayvenkat** [redhat-nfvpe/kube-ansible#78]
Hi @dougbtv, 

Firstly, thank you for your awesome work here. Using your playbooks I'm able to deploy a kubernetes cluster with pod network set to flannel. However, I'm unable to get the multus network plugin to work. 

The minion nodes come up but the master does not come up? Any help would be greatly appreciated. I have a similar problem with the "weave" pod_network_type as well for which I'll open another issue. 
Thanks.

**Comment by vinayvenkat** [comment]
What is also happening is that the /etc/cni/net.d/10-multus.conf file is not being copied onto the master. It gets copied on the minions but not on the master. 

```
[centos@k8s-master-1 ~]$ kubectl get nodes
NAME           STATUS     ROLES     AGE       VERSION
k8s-master-1   NotReady   master    12m       v1.8.1
k8s-minion-1   Ready      <none>    11m       v1.8.1
k8s-minion-2   Ready      <none>    11m       v1.8.1
```

**Comment by dougbtv** [comment]
Thanks for the report! Take a look at the branches -- there should be one
that's called "fix multus" or something like that. It should deploy a stock
multus for you.

It's not merged because there's a few things to touch up to get CRDs
working with it. But it should work as-is, it deploys a fairly static
configuration for it, but the pieces should wind up in play.

**Comment by vinayvenkat** [comment]
Thanks @dougbtv . I'll give that a try. Also do you have any examples of being able to deploy a plugin chain? What I would like to do is to deploy a CNI plugin config file to say have the following config:
```
{
  "name": "cni0",
   "plugins": [
         {
            "type": "flannel",
             .....        
          },
          {
              "type": "custom plugin",
               ..... 
          }
    ]
}
```

When I tried this with the flannel plugin it failed. Apparently there is some bug wherein flannel does not pass the right return values and parameters to the chained plugin. Which is why I wanted to try the weave plugin but that didn't work. Can it work with the multus plugin? 
Thanks.

**Comment by dougbtv** [comment]
Great question regarding the [cni network configuration lists](https://github.com/containernetworking/cni/blob/master/SPEC.md#network-configuration-lists) :smile: you're into some good container networking stuff here!! ...I have only just started to take a look at that functionality, but, haven't yet had it functioning. I plan on trying in a CNI development environment first, but, at some point should get the functionality automated in this repository too. I'll reply here when I make headway.

**Comment by dougbtv** [comment]
@vinayvenkat -- just wanted to let you know that we have the latest Multus working, now included in the master branch of this repo with PR #97 -- it also includes CRD functionality of Multus as well. However, it is sparsely documented, which we'll fix in the future.

Thanks again for submitting the issue!
