### ISSUE TITLE
Deploying a k8's cluster with pod_network_type == "weave" does not work. The nodes do not transition to the ready state. 

### ISSUE THREAD

**Issue by vinayvenkat** [redhat-nfvpe/kube-ansible#79]
I tried to deploy a k8's cluster with the pod_network_type set to "weave". When this is deployed the nodes do not transition to the Ready state. 

The status of the nodes is shown below:

[centos@k8s-master-1 ~]$ kubectl get nodes
NAME           STATUS     ROLES     AGE       VERSION
k8s-master-1   NotReady   master    1m        v1.8.1
k8s-minion-1   NotReady   <none>    32s       v1.8.1
k8s-minion-2   NotReady   <none>    32s       v1.8.1

I'm not sure where to start looking. Any pointers will be greatly appreciated. Thank you so much!

**Comment by dougbtv** [comment]
Thanks again @vinayvenkat -- we've got this noted in #21 -- been sitting out here needing attention for a while. I'm going to add your comment there, and we can track it there. Feel free to subscribe to notifications on that issue, too.
