### ISSUE TITLE
Document how to spin up kucean lab

### ISSUE THREAD

**Issue by leifmadsen** [redhat-nfvpe/kube-ansible#87]
Our documentation and blog posts could really use a refresh. Go through the documentation and create a new set of documentation / clean up README so that people can easily approach the configuration of this environment locally.

Assume we're going to be doing this with a virtual machine using KVM.

**Comment by leifmadsen** [comment]
@dougbtv can you link me to the virthost builder playbooks so that I can test those as well?

**Comment by dougbtv** [comment]
Virthost builder playbooks? Sorry I missed that, ummm, at least herein, there's two roles that I think count...

"virt host basics" -- which is like the package installs: https://github.com/redhat-nfvpe/kube-centos-ansible/tree/master/roles/virthost-basics

then there's the "vm spinup" -- https://github.com/redhat-nfvpe/kube-centos-ansible/tree/master/roles/vm-spinup

oh, and vm-teardown, too.
